INSERT INTO Car(CAR_ID,CAR_BRAND,CAR_MODEL,CAR_YEAR) VALUES ('1','Audi','RS7','2020');
INSERT INTO Car(CAR_ID,CAR_BRAND,CAR_MODEL,CAR_YEAR) VALUES ('2','BMW','m6','2019');
INSERT INTO Car(CAR_ID,CAR_BRAND,CAR_MODEL,CAR_YEAR) VALUES ('3','Mercedes','cls63','2018');

INSERT INTO Person VALUES ('22','Mohamad');